const randomEmployees = [
  {
    name: { title: "Miss", first: "Britney", last: "Sims" },
    location: {
      street: { number: 9617, name: "Tara Street" },
      city: "Dublin",
      state: "Westmeath",
      country: "Ireland",
      postcode: 66909,
      coordinates: { latitude: "17.2334", longitude: "88.9196" },
      timezone: { offset: "+4:30", description: "Kabul" },
    },
    email: "britney.sims@example.com",
    phone: "011-578-8963",
    picture: {
      large: "https://randomuser.me/api/portraits/women/62.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/62.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/62.jpg",
    },
  },
  {
    name: { title: "Ms", first: "Imogen", last: "Edwards" },
    location: {
      street: { number: 7394, name: "Durham Street" },
      city: "Dunedin",
      state: "Canterbury",
      country: "New Zealand",
      postcode: 21471,
      coordinates: { latitude: "-34.9050", longitude: "-113.6840" },
      timezone: {
        offset: "+9:00",
        description: "Tokyo, Seoul, Osaka, Sapporo, Yakutsk",
      },
    },
    email: "imogen.edwards@example.com",
    phone: "(179)-998-3204",
    picture: {
      large: "https://randomuser.me/api/portraits/women/95.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/95.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/95.jpg",
    },
  },
  {
    name: { title: "Ms", first: "Lillian", last: "Simmmons" },
    location: {
      street: { number: 1317, name: "Ormond Quay" },
      city: "Ballinasloe",
      state: "Cork City",
      country: "Ireland",
      postcode: 87859,
      coordinates: { latitude: "38.1694", longitude: "-93.8184" },
      timezone: {
        offset: "+9:00",
        description: "Tokyo, Seoul, Osaka, Sapporo, Yakutsk",
      },
    },
    email: "lillian.simmmons@example.com",
    phone: "041-937-8293",
    picture: {
      large: "https://randomuser.me/api/portraits/women/74.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/74.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/74.jpg",
    },
  },
  {
    name: { title: "Ms", first: "Jessica", last: "Torres" },
    location: {
      street: { number: 3685, name: "The Grove" },
      city: "City of London",
      state: "Humberside",
      country: "United Kingdom",
      postcode: "GP1N 0XE",
      coordinates: { latitude: "67.9751", longitude: "-132.6000" },
      timezone: {
        offset: "+5:30",
        description: "Bombay, Calcutta, Madras, New Delhi",
      },
    },
    email: "jessica.torres@example.com",
    phone: "016974 94194",
    picture: {
      large: "https://randomuser.me/api/portraits/women/63.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/63.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/63.jpg",
    },
  },
  {
    name: { title: "Mr", first: "Gumesindo", last: "Pires" },
    location: {
      street: { number: 8594, name: "Rua São Luiz " },
      city: "Petrolina",
      state: "Rio Grande do Norte",
      country: "Brazil",
      postcode: 54037,
      coordinates: { latitude: "22.6135", longitude: "153.7383" },
      timezone: {
        offset: "+5:00",
        description: "Ekaterinburg, Islamabad, Karachi, Tashkent",
      },
    },
    email: "gumesindo.pires@example.com",
    phone: "(34) 8655-6041",
    picture: {
      large: "https://randomuser.me/api/portraits/men/19.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/19.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/19.jpg",
    },
  },
  {
    name: { title: "Mrs", first: "Renata", last: "Beekmans" },
    location: {
      street: { number: 1651, name: "Horststraat" },
      city: "Zuid-Scharwoude",
      state: "Gelderland",
      country: "Netherlands",
      postcode: 18260,
      coordinates: { latitude: "42.6174", longitude: "151.4290" },
      timezone: { offset: "-10:00", description: "Hawaii" },
    },
    email: "renata.beekmans@example.com",
    phone: "(265)-906-3558",
    picture: {
      large: "https://randomuser.me/api/portraits/women/85.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/85.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/85.jpg",
    },
  },
  {
    name: { title: "Mr", first: "Karl-Friedrich", last: "Wein" },
    location: {
      street: { number: 4897, name: "Goethestraße" },
      city: "Murrhardt",
      state: "Sachsen-Anhalt",
      country: "Germany",
      postcode: 64875,
      coordinates: { latitude: "-1.6354", longitude: "174.7481" },
      timezone: { offset: "+3:30", description: "Tehran" },
    },
    email: "karl-friedrich.wein@example.com",
    phone: "0692-9320979",
    picture: {
      large: "https://randomuser.me/api/portraits/men/41.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/41.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/41.jpg",
    },
  },
  {
    name: { title: "Mr", first: "Fatih", last: "Keseroğlu" },
    location: {
      street: { number: 6250, name: "Necatibey Cd" },
      city: "Giresun",
      state: "Kars",
      country: "Turkey",
      postcode: 26185,
      coordinates: { latitude: "-35.2357", longitude: "53.1422" },
      timezone: {
        offset: "+10:00",
        description: "Eastern Australia, Guam, Vladivostok",
      },
    },
    email: "fatih.keseroglu@example.com",
    phone: "(757)-549-9011",
    picture: {
      large: "https://randomuser.me/api/portraits/men/8.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/8.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/8.jpg",
    },
  },
  {
    name: { title: "Ms", first: "Sarah", last: "Addy" },
    location: {
      street: { number: 1380, name: "St. Catherine St" },
      city: "Kingston",
      state: "Nova Scotia",
      country: "Canada",
      postcode: "M0X 4I1",
      coordinates: { latitude: "-32.3459", longitude: "-82.0403" },
      timezone: {
        offset: "+5:30",
        description: "Bombay, Calcutta, Madras, New Delhi",
      },
    },
    email: "sarah.addy@example.com",
    phone: "079-802-1624",
    picture: {
      large: "https://randomuser.me/api/portraits/women/40.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/40.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/40.jpg",
    },
  },
  {
    name: { title: "Ms", first: "Kaitlin", last: "Reid" },
    location: {
      street: { number: 2339, name: "Springfield Road" },
      city: "Kinsale",
      state: "Cork",
      country: "Ireland",
      postcode: 50937,
      coordinates: { latitude: "-85.4682", longitude: "152.8903" },
      timezone: {
        offset: "+11:00",
        description: "Magadan, Solomon Islands, New Caledonia",
      },
    },
    email: "kaitlin.reid@example.com",
    phone: "041-485-3814",
    picture: {
      large: "https://randomuser.me/api/portraits/women/19.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/19.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/19.jpg",
    },
  },
  {
    name: { title: "Ms", first: "Frida", last: "Møller" },
    location: {
      street: { number: 8774, name: "Egevej" },
      city: "Sørvad",
      state: "Sjælland",
      country: "Denmark",
      postcode: 75313,
      coordinates: { latitude: "49.7759", longitude: "58.6079" },
      timezone: {
        offset: "0:00",
        description: "Western Europe Time, London, Lisbon, Casablanca",
      },
    },
    email: "frida.moller@example.com",
    phone: "01690765",
    picture: {
      large: "https://randomuser.me/api/portraits/women/62.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/62.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/62.jpg",
    },
  },
  {
    name: { title: "Mr", first: "Edmero", last: "Nogueira" },
    location: {
      street: { number: 4636, name: "Rua Vinte E Quatro de Outubro" },
      city: "Goiânia",
      state: "Paraná",
      country: "Brazil",
      postcode: 38419,
      coordinates: { latitude: "-15.9673", longitude: "-173.0196" },
      timezone: { offset: "+7:00", description: "Bangkok, Hanoi, Jakarta" },
    },
    email: "edmero.nogueira@example.com",
    phone: "(54) 0193-5303",
    picture: {
      large: "https://randomuser.me/api/portraits/men/53.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/53.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/53.jpg",
    },
  },
  {
    name: { title: "Miss", first: "Amanda", last: "Halla" },
    location: {
      street: { number: 6058, name: "Myllypuronkatu" },
      city: "Rusko",
      state: "Central Ostrobothnia",
      country: "Finland",
      postcode: 63331,
      coordinates: { latitude: "23.8547", longitude: "2.3463" },
      timezone: { offset: "-1:00", description: "Azores, Cape Verde Islands" },
    },
    email: "amanda.halla@example.com",
    phone: "04-651-923",
    picture: {
      large: "https://randomuser.me/api/portraits/women/84.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/84.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/84.jpg",
    },
  },
  {
    name: { title: "Mr", first: "Atakan", last: "Beerendonk" },
    location: {
      street: { number: 3036, name: "Bergvink" },
      city: "Nieuwendam",
      state: "Noord-Brabant",
      country: "Netherlands",
      postcode: 92043,
      coordinates: { latitude: "-23.1677", longitude: "25.6915" },
      timezone: { offset: "+4:30", description: "Kabul" },
    },
    email: "atakan.beerendonk@example.com",
    phone: "(049)-229-8718",
    picture: {
      large: "https://randomuser.me/api/portraits/men/40.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/40.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/40.jpg",
    },
  },
  {
    name: { title: "Miss", first: "Özsu", last: "Körmükçü" },
    location: {
      street: { number: 8933, name: "Maçka Cd" },
      city: "İzmir",
      state: "Trabzon",
      country: "Turkey",
      postcode: 48079,
      coordinates: { latitude: "5.9003", longitude: "-12.7073" },
      timezone: {
        offset: "+5:00",
        description: "Ekaterinburg, Islamabad, Karachi, Tashkent",
      },
    },
    email: "ozsu.kormukcu@example.com",
    phone: "(837)-048-1605",
    picture: {
      large: "https://randomuser.me/api/portraits/women/59.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/59.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/59.jpg",
    },
  },
];

const departments = [
  "Engineering",
  "Marketing",
  "Business Development",
  "Human Resources",
];

const jobTitles = [
  "Software Engineer",
  "Engineering Manager",
  "VP of Engineering",
  "CTO",
  "CEO",
  "Product Manager",
  "UX Designer",
  "Director of Product Design",
  "Administrative Assistant",
  "Director of Marketing",
  "Copywriter",
  "Designer",
  "Sales Coordinator",
];

const interests = [
  "Hiking",
  "Hot sauces",
  "Guitar",
  "Cycling",
  "Wine",
  "Cats",
  "Dogs",
];

module.exports = { randomEmployees, departments, jobTitles, interests };
